---
title: "progress-report-izzygrabowski03.Rmd"
author: "Izzy Grabowski"
date: "2025-04-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(dplyr)


url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"

html <- read_html(url)


tables <- html %>% html_table(fill=TRUE)


length(tables)

#first table
hof_2025_raw <- tables[[1]]

head(hof_2025_raw)

head(tables[[1]], 3)
```

```{r}

data <- tables[[1]]
actual_col_names <- data[1, ]
colnames(data) <- actual_col_names
data <- data[-1, ]
head(data, 3)

data$Votes <- as.numeric(data$Votes)
data$Votes

library(rvest)
library(dplyr)
library(readr)
library(tidyr)
library(Lahman)

url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
tables <- html_table(html, fill = TRUE)
raw_data <- tables[[1]]

actual_colnames <- as.character(unlist(raw_data[1, ]))
colnames(raw_data) <- make.names(actual_colnames, unique = TRUE)
data <- raw_data[-1, ]

data_cleaned <- data %>%
  mutate(
    Votes = parse_number(Votes),
    Percent = parse_number(X.vote)
  ) %>%
  mutate(
    ballots = sum(Votes, na.rm = TRUE),
    needed = ceiling(0.75 * ballots),
    inducted = ifelse(Percent >= 75, "Y", "N")
  ) %>%
  separate(Name, into = c("firstName", "lastName"), sep = " ", extra = "merge") %>%
  left_join(
    People %>% select(playerID, nameFirst, nameLast),
    by = c("firstName" = "nameFirst", "lastName" = "nameLast")
  )

final_cleaned <- data_cleaned %>%
  mutate(
    votedBy = "BBWAA",
    yearID = 2025,
    category = "Player",
    needed_note = NA_character_
  ) %>%
  select(
    playerID, yearID, votedBy, ballots, needed,
    votes = Votes, inducted, category, needed_note
  )

head(final_cleaned)

```
```{r}

library(tidyverse)
library(Lahman)

# View the original HallOfFame data
head(HallOfFame)






```















