---
title: "progress-report-Mooseley03"
author: "Christopher Moseley"
date: "2025-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(rvest)
library(dplyr)
library(stringr)
library(stringi)
library(Lahman)
library(ggplot2)
url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
tables <- html_table(html)
tables
```

```{r}
# scrape data
url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
data <- read_html(url) %>% html_table() %>% .[[1]]

# fix column names
colnames(data) <- make.names(data[1, ], unique = TRUE)
data <- data[-1, ]

# keep necessary columns
data <- data %>%
  mutate(
    Votes = as.numeric(Votes),
    Name = as.character(Name)
  ) %>%
  select(Name, Votes)

# Prep entries
hof_2025 <- data %>%
  mutate(
    yearID = 2025,
    votedBy = "BBWAA",
    ballots = 394,
    needed = 296,
    inducted = ifelse(Votes >= 292, "Y", "N"),
    category = NA,
    needed_note = NA
  ) %>%
  left_join(
    People %>%
      mutate(Name = paste(nameFirst, nameLast)) %>%
      select(playerID, Name),
    by = "Name"
  ) %>%
  select(playerID, yearID, votedBy, ballots, needed, votes = Votes,
         inducted, category, needed_note)

# Add 2025 columns to previous information
hof_all <- bind_rows(Lahman::HallOfFame, hof_2025)

# check dataset
head(hof_all)

# save dataset
# readr::write_csv(hof_all, file = "hof_all_2025.csv")
```

```{r}
# plot data
hof_all %>%
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2025))
```
